### ISSUE TITLE
Add test for ad clinent

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-forecast-app#92]
Add test for ad client

This was skipped in #90

**Comment by Sukh-P** [comment]
So related to this issue and something perhaps to address alongside this or in another issue/PR is that I noticed that for pv sites we currently aren't testing against our actual models and instead are using the dummy model https://github.com/openclimatefix/india-forecast-app/blob/main/tests/test_app.py#L81 which generates fake predictions, I imagine this was done previously when pv models weren't quite ready but perhaps now it would be good to remove this? Let me know what you think @peterdudfield

**Comment by peterdudfield** [comment]
> So related to this issue and something perhaps to address alongside this or in another issue/PR is that I noticed that for pv sites we currently aren't testing against our actual models and instead are using the dummy model https://github.com/openclimatefix/india-forecast-app/blob/main/tests/test_app.py#L81 which generates fake predictions, I imagine this was done previously when pv models weren't quite ready but perhaps now it would be good to remove this? Let me know what you think @peterdudfield

yea, good to remove this, perhaps in a different PR. Need to think if we remove the dummy model all together, or just leave it as its useful for testing e.t.c

**Comment by Sukh-P** [comment]
So started to look at this and realised why I had originally skipped it, it's a bit tricky to test the ad model since it is in a private repo on HF and we would need to supply a token for running tests locally and in CI, did you have some thoughts already @peterdudfield on how to approach this? I had an idea but might be slightly over-engineered:

- Add a pytest marker to the ad test so it's marked differently to the other tests, that way you can run the others tests easily locally and give some extra info on how to run that one locally (it would not be run by default locally) 
- When it is ran locally the person running it will need to set the HF token first as an env variable, can add this to the docs
- In Github actions I believe we can add the HF token as a secret and then this can be accessed/set as the environment variable so it should pass there, may need some code change as well, not sure

The other option is some sort of mocking but I can't think what part would be mocked that it would actually test the model in a meaningful way, let me know your thoughts! Thanks

**Comment by peterdudfield** [comment]
Yea, we cant share that model as its private. 

1. a pytest marker would be great
2. Yea, I would suggest only OCF people can run this. At least for the moment
3. Yea, we can add token in environment so it runs. 

Yea mocking will be hard.
